# Site settings
title: Dennis Wong
academic_email: 

description: > # this means to ignore newlines until "baseurl:"

baseurl: "/" # the subpath of your site, e.g. /blog/

url: "https://d18w.github.io" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax
